name: CSV Pipeline



on:

  push:

    branches:

      - main

  workflow_dispatch:
    inputs:
      env:
        description: 'Sélectionner l’environnement'
        required: true
        default: 'dev'


jobs:

  csv_pipeline:

    runs-on: ubuntu-latest



    strategy:

      matrix:

        env: [dev, test, prod]
	python-version: [3.10, 3.11]



    steps:

      - name: Checkout repository

        uses: actions/checkout@v3



      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.11'



      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install pandas  # ou toute autre dépendance nécessaire



      - name: Run Python script for ${{ matrix.env }}

        run: |

          if [ "${{ matrix.env }}" == "dev" ]; then

            python scripts/csv_to_dev.py

          elif [ "${{ matrix.env }}" == "test" ]; then

            python scripts/csv_to_test.py

          elif [ "${{ matrix.env }}" == "prod" ]; then

            python scripts/csv_to_prod.py

          fi

	 
